Update hipGetBackendNativeHandles use
CHIP-SPV/H4I-HipBLAS pull request #17
Opened 2024-02-28 23:28 UTC by pvelesko

2024-03-04 05:49 UTC, Sarbojit2019 requested changes
Add a check to make sure chipStar is compatible.

2024-03-04 05:49 UTC, Sarbojit2019 commented on src/util.cpp
> +        int nHandles;
These are backward compatibility breaking changes. We should add a check to verify chipStar is compatible. Think of a situation where chipStar runtime is old but hipBlas is new.

2024-04-10 08:38 UTC, pvelesko commented
made this backwards compatible with HIP 6.x

2024-04-16 11:25 UTC, Sarbojit2019 approved these changes
Looks ok to me

2024-04-16 11:25 UTC, merged